server:
  port: 8081

spring:
  application:
    name: async-job-ingestion-producer
  datasource:
    url: jdbc:mysql://localhost:3306/job
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable-idempotence: true
        max-in-flight-requests-per-connection: 5
        spring.json.type.mapping: jobRequest:com.anurag.AsyncJobInjestionProducer.DTO.JobRequest
      retries: 10
      acks: all

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true